# -*- coding: utf-8 -*-
""" Translation of labels between English and Japanese.
"""
label_to_japanese = {
    u"レミリア・スカーレット": u"レミリア・スカーレット",
    u"諏訪子": u"洩矢諏訪子",
    u"KAITO": "KAITO",
    u"松岡凛": u"松岡凛",
    u"シンタロー": u"如月シンタロー",
    u"沖田総悟": u"沖田総悟",
    u"ピカチュウ": u"ピカチュウ",
    u"鍵山雛": u"鍵山雛",
    u"魂魄妖夢": u"魂魄妖夢",
    u"鬼灯": u"鬼灯",
    u"フランドール・スカーレット": u"フランドール・スカーレット",
    u"エレン・イェーガー": u"エレン・イェーガー",
    u"高尾和成": u"高尾和成",
    u"てゐ": u"因幡てゐ",
    u"暁美ほむら": u"暁美ほむら",
    u"お空": u"霊烏路空",
    u"真田幸村": u"真田幸村",
    u"赤司征十郎": u"赤司征十郎",
    u"アヤノ": u"アヤノ",
    u"長曾我部元親": u"長曾我部元親",
    u"八雲紫": u"八雲紫",
    u"橘真琴": u"橘真琴",
    u"紅美鈴": u"紅美鈴",
    u"七瀬遙": u"七瀬遙",
    u"鹿目まどか": u"鹿目まどか",
    u"伊吹萃香": u"伊吹萃香",
    u"小悪魔": u"小悪魔",
    u"犬走椛": u"犬走椛",
    u"アラジン": u"アラジン",
    u"古明地さとり": u"古明地さとり",
    u"射命丸文": u"射命丸文",
    u"毛利元就": u"毛利元就",
    u"緑間真太郎": u"緑間真太郎",
    u"西行寺幽々子": u"西行寺幽々子",
    u"ルートヴィッヒ": u"ルートヴィッヒ",
    u"ゾロ": u"ロロノア・ゾロ",
    u"菊地真": u"菊地真",
    u"巴マミ": u"巴マミ",
    u"平沢唯": u"平沢唯",
    u"神楽": u"神楽",
    u"ロヴィーノ・ヴァルガス": u"ロヴィーノ・ヴァルガス",
    u"トラファルガー・ロー": u"トラファルガー・ロー",
    u"奥村燐": u"奥村燐",
    u"うどんげ": u"鈴仙・優曇華院・イナバ",
    u"霧野蘭丸": u"霧野蘭丸",
    u"天海春香": u"天海春香",
    u"チルノ": u"チルノ",
    u"黒子テツヤ": u"黒子テツヤ",
    u"佐倉杏子": u"佐倉杏子",
    u"鏡音リン": u"鏡音リン",
    u"サンジ": u"サンジ",
    u"巡音ルカ": u"巡音ルカ",
    u"石田三成": u"石田三成",
    u"碇シンジ": u"碇シンジ",
    u"イヴァン・ブラギンスキ": u"イヴァン・ブラギンスキ",
    u"フェリシアーノ・ヴァルガス": u"フェリシアーノ・ヴァルガス",
    u"アリババ": u"アリババ",
    u"十六夜咲夜": u"十六夜咲夜",
    u"カノ": u"カノ",
    u"白澤": u"白澤",
    u"大妖精": u"大妖精",
    u"ルーミア": u"ルーミア",
    u"折原臨也": u"折原臨也",
    u"徳川家康": u"徳川家康",
    u"土方十四郎": u"土方十四郎",
    u"パチュリー": u"パチュリー・ノーレッジ",
    u"伊達政宗": u"伊達政宗",
    u"東風谷早苗": u"東風谷早苗",
    u"アルフレッド・F・ジョーンズ": u"アルフレッド・F・ジョーンズ",
    u"藤原妹紅": u"藤原妹紅",
    u"ミカサ・アッカーマン": u"ミカサ・アッカーマン",
    u"キュゥべえ": u"キュゥべえ",
    u"神威がくぽ": u"神威がくぽ",
    u"風見幽香": u"風見幽香",
    u"初音ミク": u"初音ミク",
    u"比那名居天子": u"比那名居天子",
    u"バーナビー・ブルックスJr.": u"バーナビー・ブルックスJr.",
    u"寅丸星": u"寅丸星",
    u"ナズーリン": u"ナズーリン",
    u"古明地こいし": u"古明地こいし",
    u"鏑木・T・虎徹": u"鏑木・T・虎徹",
    u"高杉晋助": u"高杉晋助",
    u"中野梓": u"中野梓",
    u"青峰大輝": u"青峰大輝",
    u"平和島静雄": u"平和島静雄",
    u"美風藍": u"美風藍",
    u"ギルベルト・バイルシュミット": u"ギルベルト・バイルシュミット",
    u"美樹さやか": u"美樹さやか",
    u"アントーニョ・ヘルナンデス・カリエド": u"アントーニョ・ヘルナンデス・カリエド",
    u"矢澤にこ": u"矢澤にこ",
    u"水橋パルスィ": u"水橋パルスィ",
    u"島風": u"島風",
    u"本田菊": u"本田菊",
    u"MEIKO": "MEIKO",
    u"八雲藍": u"八雲藍",
    u"橙": u"橙",
    u"秋山澪": u"秋山澪",
    u"ルフィ": u"モンキー・D・ルフィ",
    u"黄瀬涼太": u"黄瀬涼太",
    u"アーサー・カークランド": u"アーサー・カークランド",
    u"坂田銀時": u"坂田銀時",
    u"鏡音レン": u"鏡音レン",
    u"博麗霊夢": u"博麗霊夢",
    u"王耀": u"王耀",
    u"封獣ぬえ": u"封獣ぬえ",
    u"アリス・マーガトロイド": u"アリス・マーガトロイド",
    u"魔理沙": u"霧雨魔理沙",
    u"セイバー": u"セイバー",
    u"リヴァイ": u"リヴァイ",
    u"田井中律": u"田井中律",
    u"渚カヲル": u"渚カヲル",
    u"フランシス・ボヌフォワ": u"フランシス・ボヌフォワ",
    u"火神大我": u"火神大我",
    u"来栖翔": u"来栖翔",
    u"紫原敦": u"紫原敦"
}
label_to_english = {
    u"レミリア・スカーレット": "Remilia Scarlet",
    u"諏訪子": "Moriyasu Suwako",
    u"KAITO": "KAITO",
    u"松岡凛": "Matsuoka Rin",
    u"シンタロー": "Kisaragi Shintaro",
    u"沖田総悟": "Okita Sougo",
    u"ピカチュウ": "Pikachu",
    u"鍵山雛": "Kagiyama Hina",
    u"魂魄妖夢": "Konpaku Youmu",
    u"鬼灯": "Hoozuki",
    u"フランドール・スカーレット": "Flandre Scarlet",
    u"エレン・イェーガー": "Eren Yeager",
    u"高尾和成": "Takao Kazunari",
    u"てゐ": "Inaba Tewi",
    u"暁美ほむら": "Akemi Homura",
    u"お空": "Reiuji Utsuho",
    u"真田幸村": "Sanada Yukimura",
    u"赤司征十郎": "Akashi Seijuurou",
    u"アヤノ": "Ayano",
    u"長曾我部元親": "Chousokabe Motochika",
    u"八雲紫": "Yakumo Yukari",
    u"橘真琴": "Tachibana Makoto",
    u"紅美鈴": "Hong Meiling",
    u"七瀬遙": "Nanase Haruka",
    u"鹿目まどか": "Kaname Madoka",
    u"伊吹萃香": "Ibuki Suika",
    u"小悪魔": "Koakuma",
    u"犬走椛": "Inubashiri Momiji",
    u"アラジン": "Aladdin",
    u"古明地さとり": "Komeiji Satori",
    u"射命丸文": "Shameimaru Aya",
    u"毛利元就": "Mouri Motonari",
    u"緑間真太郎": "Midorima Shintarou",
    u"西行寺幽々子": "Saigyouji Yuyuko",
    u"ルートヴィッヒ": "Ludwig",
    u"ゾロ": "Roronoa Zoro",
    u"菊地真": "Kikuchi Makoto",
    u"巴マミ": "Tomoe Mami",
    u"平沢唯": "Hirasawa Yui",
    u"神楽": "Kagura",
    u"ロヴィーノ・ヴァルガス": "Lovino Vargas",
    u"トラファルガー・ロー": "Trafalgar Law",
    u"奥村燐": "Okumura Rin",
    u"うどんげ": "Reisen Udongein Inaba",
    u"霧野蘭丸": "Kirino Ranmaru",
    u"天海春香": "Amami Haruka",
    u"チルノ": "Cirno",
    u"黒子テツヤ": "Kuroko Testsuya",
    u"佐倉杏子": "Sakura Kyouko",
    u"鏡音リン": "Kagamine Rin",
    u"サンジ": "Sanji",
    u"巡音ルカ": "Megurine Luka",
    u"石田三成": "Ishida Mitsunari",
    u"碇シンジ": "Ikari Shinji",
    u"イヴァン・ブラギンスキ": "Ivan Braginsky",
    u"フェリシアーノ・ヴァルガス": "Feliciano Vargas",
    u"アリババ": "Alibaba",
    u"十六夜咲夜": "Izayoi Sakuya",
    u"カノ": "Kano",
    u"白澤": "Hakutaku",
    u"大妖精": "Daiyousei",
    u"ルーミア": "Rumia",
    u"折原臨也": "Orihara Izaya",
    u"徳川家康": "Tokugawa Ieyasu",
    u"土方十四郎": "Ijikata Toushirou",
    u"パチュリー": "Patchouli Knowledge",
    u"伊達政宗": "Date Masamune",
    u"東風谷早苗": "Kochiya Sanae",
    u"アルフレッド・F・ジョーンズ": "Alfred F. Jones",
    u"藤原妹紅": "Fujiwara no Mokou",
    u"ミカサ・アッカーマン": "Mikasa Ackerman",
    u"キュゥべえ": "Kyubey",
    u"神威がくぽ": "Kamui Gakupo",
    u"風見幽香": "Kazami Yuuka",
    u"初音ミク": "Hatsune Miku",
    u"比那名居天子": "Hinanawi Tenshi",
    u"バーナビー・ブルックスJr.": "Barnaby Brooks Jr.",
    u"寅丸星": "Toramaru Shou",
    u"ナズーリン": "Nazrin",
    u"古明地こいし": "Komeiji Koishi",
    u"鏑木・T・虎徹": "Kaburagi T. Kotetsu",
    u"高杉晋助": "Takasugi Shinsuke",
    u"中野梓": "Nakano Azusa",
    u"青峰大輝": "Aomine Daiki",
    u"平和島静雄": "Heiwajima Shizuo",
    u"美風藍": "Mikaze Ai",
    u"ギルベルト・バイルシュミット": "Gilbert Beilschmidt",
    u"美樹さやか": "Miki Sayaka",
    u"アントーニョ・ヘルナンデス・カリエド": "Antonio Hernández Carriedo",
    u"矢澤にこ": "Yazawa Nico",
    u"水橋パルスィ": "Mizuhashi Parsee",
    u"島風": "Shimakaze",
    u"本田菊": "Honda Kiku",
    u"MEIKO": "MEIKO",
    u"八雲藍": "Yakumo Ran",
    u"橙": "Chen",
    u"秋山澪": "Akiyama Mio",
    u"ルフィ": "Monkey D. Luffy",
    u"黄瀬涼太": "Kise Ryouta",
    u"アーサー・カークランド": "Arthur Kirkland",
    u"坂田銀時": "Sakata Gintoki",
    u"鏡音レン": "Kagamine Ren",
    u"博麗霊夢": "Hakurei Reimu",
    u"王耀": "Wang Yao",
    u"封獣ぬえ": "Houjuu Nue",
    u"アリス・マーガトロイド": "Alice Margatroid",
    u"魔理沙": "Kirisame Marisa",
    u"セイバー": "Saber",
    u"リヴァイ": "Levi",
    u"田井中律": "Tainaka Ritsu",
    u"渚カヲル": "Nagisa Kaoru",
    u"フランシス・ボヌフォワ": "Francis Bonnefoy",
    u"火神大我": "Kagami Taiga",
    u"来栖翔": "Kurusu Shou",
    u"紫原敦": "Murasakibara Atsushi"
}
